apiVersion: v1
kind: Service
metadata:
  name: gen-algo-webui
  # namespace: gen-algo
  labels:
    app: gen-algo-webui
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: gen-algo-webui
