apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-algo-webui
  # namespace: gen-algo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gen-algo-webui
  template:
    spec:
      containers:
        - name: frontend
          image: demarauder/gen-algo-webui:latest-main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
