apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-dev-us-east-1
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://helm.releases.hashicorp.com"
      chart: vault
      targetRevision: 0.28.0
      helm:
        valueFiles:
          - $values/manifests/helm/dev/vault-values.yaml
    - repoURL: "https://github.com/de-marauder/multi-region-eks"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    # namespace: gen-algo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
