apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: gen-algo
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/multi-region-deployment'
    targetRevision: HEAD
    path: hashicorp/vault
    helm:
      valueFiles:
        - manifests/helm/dev/vault-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
