apiVersion: apps/v1
kind: Deployment
metadata:
  name: gen-algo-webui
  namespace: gen-algo
spec:
  selector:
    matchLabels:
      app: gen-algo-webui
  template:
    spec:
        containers:
          - name: backend
            image: demarauder/gen-algo-webui:latest-main
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"